layout_spectrum: 1
favicon: null
name: Olling Glass
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  lightness: 0.3330523
  saturation: 0.3279932
  rhythmicContrast: 1
  brandColors:
    - '#000000'
    - '#FCFCFB'
    - '#424242'
    - '#929191'
typography_spectrum: 0.6787521
