name: Olling Glass
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6787521
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#850100'
    - '#d93903'
    - '#fe8e40'
  brandStrength: 1
  lightness: 0.3330523
  saturation: 0.3279932
  rhythmicContrast: 1
purpose: []
