name: Olling Glass
favicon: null
layout_spectrum: 0.75315
typography_spectrum: 0.6787521
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0e'
    - '#a2a19d'
    - '#312c33'
    - '#fffeff'
    - '#cedfd5'
  brandStrength: 0
  lightness: 0.3330523
  saturation: 0.3279932
  rhythmicContrast: 1
purpose: []
